import { User } from "@/models/user";

const DUMMY_USERS: User[] = [
  {
    id: "1",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    name: "Ole",
    family: "Hansen",
    role: "admin",
    isOwner: true,
    email: "ole.hansen@example.com",
    createdOn: "2023-01-01",
    countryCode: "+47",
    phone: "12345678",
    status: "active",
  },
  {
    id: "2",
    image: undefined,
    name: "Kari",
    family: "Svendsen",
    role: "electrician",
    isOwner: false,
    email: "kari.svendsen@example.com",
    createdOn: "2023-01-02",
    countryCode: "+47",
    phone: "23456789",
    status: "inactive",
  },
  {
    id: "3",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
    name: "Per",
    family: "Pedersen",
    role: "project manager",
    isOwner: false,
    email: "per.pedersen@example.com",
    createdOn: "2023-01-03",
    countryCode: "+47",
    phone: "34567890",
    status: "blocked",
  },
  {
    id: "4",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    name: "Ingrid",
    family: "Johansen",
    role: "technical manager",
    isOwner: false,
    email: "ingrid.johansen@example.com",
    createdOn: "2023-01-04",
    countryCode: "+47",
    phone: "45678901",
    status: "invited",
  },
  {
    id: "5",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    name: "Erik",
    family: "Olsen",
    role: "supervisor",
    isOwner: false,
    email: "erik.olsen@example.com",
    createdOn: "2023-01-05",
    countryCode: "+47",
    phone: "56789012",
    status: "active",
  },
  {
    id: "6",
    image: "https://randomuser.me/api/portraits/men/6.jpg",
    name: "Andreas",
    family: "Andersen",
    role: "admin",
    isOwner: false,
    email: "andreas.andersen@example.com",
    createdOn: "2023-01-06",
    countryCode: "+47",
    phone: "67890123",
    status: "active",
  },
  {
    id: "7",
    image: "https://randomuser.me/api/portraits/women/7.jpg",
    name: "Marianne",
    family: "Madsen",
    role: "electrician",
    isOwner: false,
    email: "marianne.madsen@example.com",
    createdOn: "2023-01-07",
    countryCode: "+47",
    phone: "78901234",
    status: "inactive",
  },
  {
    id: "8",
    image: "https://randomuser.me/api/portraits/men/8.jpg",
    name: "Jens",
    family: "Jensen",
    role: "project manager",
    isOwner: false,
    email: "jens.jensen@example.com",
    createdOn: "2023-01-08",
    countryCode: "+47",
    phone: "89012345",
    status: "blocked",
  },
  {
    id: "9",
    image: "https://randomuser.me/api/portraits/women/9.jpg",
    name: "Ida",
    family: "Ida",
    role: "technical manager",
    isOwner: false,
    email: "ida.ida@example.com",
    createdOn: "2023-01-09",
    countryCode: "+47",
    phone: "90123456",
    status: "invited",
  },
  {
    id: "10",
    image: "https://randomuser.me/api/portraits/men/10.jpg",
    name: "Jon",
    family: "Jonassen",
    role: "supervisor",
    isOwner: false,
    email: "jon.jonassen@example.com",
    createdOn: "2023-01-10",
    countryCode: "+47",
    phone: "01234567",
    status: "active",
  },
  {
    id: "11",
    image: "https://randomuser.me/api/portraits/men/11.jpg",
    name: "Per",
    family: "Persen",
    role: "admin",
    isOwner: false,
    email: "per.persen@example.com",
    createdOn: "2023-01-11",
    countryCode: "+47",
    phone: "12345678",
    status: "active",
  },
  {
    id: "12",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
    name: "Ingrid",
    family: "Ingridsen",
    role: "electrician",
    isOwner: false,
    email: "ingrid.ingridsen@example.com",
    createdOn: "2023-01-12",
    countryCode: "+47",
    phone: "23456789",
    status: "inactive",
  },
  {
    id: "13",
    image: "https://randomuser.me/api/portraits/men/13.jpg",
    name: "Erik",
    family: "Eriksen",
    role: "project manager",
    isOwner: false,
    email: "erik.eriksen@example.com",
    createdOn: "2023-01-13",
    countryCode: "+47",
    phone: "34567890",
    status: "blocked",
  },
  {
    id: "14",
    image: "https://randomuser.me/api/portraits/women/14.jpg",
    name: "Anna",
    family: "Annasen",
    role: "technical manager",
    isOwner: false,
    email: "anna.annasen@example.com",
    createdOn: "2023-01-14",
    countryCode: "+47",
    phone: "45678901",
    status: "invited",
  },
  {
    id: "15",
    image: "https://randomuser.me/api/portraits/men/15.jpg",
    name: "Ole",
    family: "Olesen",
    role: "supervisor",
    isOwner: false,
    email: "ole.olesen@example.com",
    createdOn: "2023-01-15",
    countryCode: "+47",
    phone: "56789012",
    status: "active",
  },
];

export default DUMMY_USERS;
